import org.drinkless.tdlib.TdApi

enum class EFunction {
    AcceptCall,
    AddChatMember,
    AddChatMembers,
    AddFavoriteSticker,
    AddNetworkStatistics,
    AddRecentSticker,
    AddRecentlyFoundChat,
    AddSavedAnimation,
    AddStickerToSet,
    AnswerCallbackQuery,
    AnswerCustomQuery,
    AnswerInlineQuery,
    AnswerPreCheckoutQuery,
    AnswerShippingQuery,
    BlockUser,
    CancelDownloadFile,
    CancelUploadFile,
    ChangeChatReportSpamState,
    ChangeImportedContacts,
    ChangePhoneNumber,
    ChangeStickerSet,
    CheckAuthenticationBotToken,
    CheckAuthenticationCode,
    CheckAuthenticationPassword,
    CheckChangePhoneNumberCode,
    CheckChatInviteLink,
    CheckChatUsername,
    CheckDatabaseEncryptionKey,
    ClearImportedContacts,
    ClearRecentStickers,
    ClearRecentlyFoundChats,
    Close,
    CloseChat,
    CloseSecretChat,
    CreateBasicGroupChat,
    CreateCall,
    CreateNewBasicGroupChat,
    CreateNewSecretChat,
    CreateNewStickerSet,
    CreateNewSupergroupChat,
    CreatePrivateChat,
    CreateSecretChat,
    CreateSupergroupChat,
    CreateTemporaryPassword,
    DeleteAccount,
    DeleteChatHistory,
    DeleteChatMessagesFromUser,
    DeleteChatReplyMarkup,
    DeleteFile,
    DeleteMessages,
    DeleteProfilePhoto,
    DeleteSavedCredentials,
    DeleteSavedOrderInfo,
    DeleteSupergroup,
    Destroy,
    DiscardCall,
    DisconnectAllWebsites,
    DisconnectWebsite,
    DownloadFile,
    EditInlineMessageCaption,
    EditInlineMessageLiveLocation,
    EditInlineMessageReplyMarkup,
    EditInlineMessageText,
    EditMessageCaption,
    EditMessageLiveLocation,
    EditMessageReplyMarkup,
    EditMessageText,
    FinishFileGeneration,
    ForwardMessages,
    GenerateChatInviteLink,
    GetAccountTtl,
    GetActiveLiveLocationMessages,
    GetActiveSessions,
    GetArchivedStickerSets,
    GetAttachedStickerSets,
    GetAuthorizationState,
    GetBasicGroup,
    GetBasicGroupFullInfo,
    GetBlockedUsers,
    GetCallbackQueryAnswer,
    GetChat,
    GetChatAdministrators,
    GetChatEventLog,
    GetChatHistory,
    GetChatMember,
    GetChatMessageByDate,
    GetChatPinnedMessage,
    GetChatReportSpamState,
    GetChats,
    GetConnectedWebsites,
    GetCountryCode,
    GetCreatedPublicChats,
    GetFavoriteStickers,
    GetFile,
    GetFileExtension,
    GetFileMimeType,
    GetGameHighScores,
    GetGroupsInCommon,
    GetImportedContactCount,
    GetInlineGameHighScores,
    GetInlineQueryResults,
    GetInstalledStickerSets,
    GetInviteText,
    GetMe,
    GetMessage,
    GetMessages,
    GetNetworkStatistics,
    GetNotificationSettings,
    GetOption,
    GetPasswordState,
    GetPaymentForm,
    GetPaymentReceipt,
    GetProxy,
    GetPublicMessageLink,
    GetRecentInlineBots,
    GetRecentStickers,
    GetRecentlyVisitedTMeUrls,
    GetRecoveryEmailAddress,
    GetRemoteFile,
    GetRepliedMessage,
    GetSavedAnimations,
    GetSavedOrderInfo,
    GetSecretChat,
    GetStickerEmojis,
    GetStickerSet,
    GetStickers,
    GetStorageStatistics,
    GetStorageStatisticsFast,
    GetSupergroup,
    GetSupergroupFullInfo,
    GetSupergroupMembers,
    GetSupportUser,
    GetTemporaryPasswordState,
    GetTermsOfService,
    GetTextEntities,
    GetTopChats,
    GetTrendingStickerSets,
    GetUser,
    GetUserFullInfo,
    GetUserPrivacySettingRules,
    GetUserProfilePhotos,
    GetWallpapers,
    GetWebPageInstantView,
    GetWebPagePreview,
    ImportContacts,
    JoinChatByInviteLink,
    LogOut,
    OpenChat,
    OpenMessageContent,
    OptimizeStorage,
    ParseTextEntities,
    PinSupergroupMessage,
    ProcessDcUpdate,
    ReadAllChatMentions,
    RecoverAuthenticationPassword,
    RecoverPassword,
    RegisterDevice,
    RemoveContacts,
    RemoveFavoriteSticker,
    RemoveRecentHashtag,
    RemoveRecentSticker,
    RemoveRecentlyFoundChat,
    RemoveSavedAnimation,
    RemoveStickerFromSet,
    RemoveTopChat,
    ReorderInstalledStickerSets,
    ReportChat,
    ReportSupergroupSpam,
    RequestAuthenticationPasswordRecovery,
    RequestPasswordRecovery,
    ResendAuthenticationCode,
    ResendChangePhoneNumberCode,
    ResetAllNotificationSettings,
    ResetNetworkStatistics,
    SearchCallMessages,
    SearchChatMembers,
    SearchChatMessages,
    SearchChatRecentLocationMessages,
    SearchChats,
    SearchChatsOnServer,
    SearchContacts,
    SearchHashtags,
    SearchInstalledStickerSets,
    SearchMessages,
    SearchPublicChat,
    SearchPublicChats,
    SearchSecretMessages,
    SearchStickerSet,
    SearchStickerSets,
    SearchStickers,
    SendBotStartMessage,
    SendCallDebugInformation,
    SendCallRating,
    SendChatAction,
    SendChatScreenshotTakenNotification,
    SendChatSetTtlMessage,
    SendCustomRequest,
    SendInlineQueryResultMessage,
    SendMessage,
    SendMessageAlbum,
    SendPaymentForm,
    SetAccountTtl,
    SetAlarm,
    SetAuthenticationPhoneNumber,
    SetBio,
    SetBotUpdatesStatus,
    SetChatClientData,
    SetChatDraftMessage,
    SetChatMemberStatus,
    SetChatPhoto,
    SetChatTitle,
    SetDatabaseEncryptionKey,
    SetFileGenerationProgress,
    SetGameScore,
    SetInlineGameScore,
    SetName,
    SetNetworkType,
    SetNotificationSettings,
    SetOption,
    SetPassword,
    SetPinnedChats,
    SetProfilePhoto,
    SetProxy,
    SetRecoveryEmailAddress,
    SetStickerPositionInSet,
    SetSupergroupDescription,
    SetSupergroupStickerSet,
    SetSupergroupUsername,
    SetTdlibParameters,
    SetUserPrivacySettingRules,
    SetUsername,
    TerminateAllOtherSessions,
    TerminateSession,
    TestCallBytes,
    TestCallEmpty,
    TestCallString,
    TestCallVectorInt,
    TestCallVectorIntObject,
    TestCallVectorString,
    TestCallVectorStringObject,
    TestGetDifference,
    TestNetwork,
    TestSquareInt,
    TestUseError,
    TestUseUpdate,
    ToggleBasicGroupAdministrators,
    ToggleChatIsPinned,
    ToggleSupergroupInvites,
    ToggleSupergroupIsAllHistoryAvailable,
    ToggleSupergroupSignMessages,
    UnblockUser,
    UnpinSupergroupMessage,
    UpgradeBasicGroupChatToSupergroupChat,
    UploadFile,
    UploadStickerFile,
    ValidateOrderInfo,
    ViewMessages,
    ViewTrendingStickerSets
}

enum class EAuthState {
    WaitTdlibParameters,
    WaitEncryptionKey,
    WaitPhoneNumber,
    WaitCode,
    WaitPassword,
    Ready,
    LoggingOut,
    Closing,
    Closed
}

enum class EUpdate {
    UpdateAuthorizationState,
    UpdateNewMessage,
    UpdateMessageSendAcknowledged,
    UpdateMessageSendSucceeded,
    UpdateMessageSendFailed,
    UpdateMessageContent,
    UpdateMessageEdited,
    UpdateMessageViews,
    UpdateMessageContentOpened,
    UpdateMessageMentionRead,
    UpdateNewChat,
    UpdateChatTitle,
    UpdateChatPhoto,
    UpdateChatLastMessage,
    UpdateChatOrder,
    UpdateChatIsPinned,
    UpdateChatReadInbox,
    UpdateChatReadOutbox,
    UpdateChatUnreadMentionCount,
    UpdateNotificationSettings,
    UpdateChatReplyMarkup,
    UpdateChatDraftMessage,
    UpdateDeleteMessages,
    UpdateUserChatAction,
    UpdateUserStatus,
    UpdateUser,
    UpdateBasicGroup,
    UpdateSupergroup,
    UpdateSecretChat,
    UpdateUserFullInfo,
    UpdateBasicGroupFullInfo,
    UpdateSupergroupFullInfo,
    UpdateServiceNotification,
    UpdateFile,
    UpdateFileGenerationStart,
    UpdateFileGenerationStop,
    UpdateCall,
    UpdateUserPrivacySettingRules,
    UpdateUnreadMessageCount,
    UpdateOption,
    UpdateInstalledStickerSets,
    UpdateTrendingStickerSets,
    UpdateRecentStickers,
    UpdateFavoriteStickers,
    UpdateSavedAnimations,
    UpdateConnectionState,
    UpdateNewInlineQuery,
    UpdateNewChosenInlineResult,
    UpdateNewCallbackQuery,
    UpdateNewInlineCallbackQuery,
    UpdateNewShippingQuery,
    UpdateNewPreCheckoutQuery,
    UpdateNewCustomEvent,
    UpdateNewCustomQuery
}

enum class ENotificationSettingScope {
    NotificationSettingsScopeChat,
    NotificationSettingsScopePrivateChats,
    NotificationSettingsScopeBasicGroupChats,
    NotificationSettingsScopeAllChats
}

val authStateMap = mapOf(
        TdApi.AuthorizationStateWaitTdlibParameters.CONSTRUCTOR to EAuthState.WaitTdlibParameters,
        TdApi.AuthorizationStateClosed.CONSTRUCTOR              to EAuthState.Closed,
        TdApi.AuthorizationStateClosing.CONSTRUCTOR             to EAuthState.Closing,
        TdApi.AuthorizationStateLoggingOut.CONSTRUCTOR          to EAuthState.LoggingOut,
        TdApi.AuthorizationStateReady.CONSTRUCTOR               to EAuthState.Ready,
        TdApi.AuthorizationStateWaitCode.CONSTRUCTOR            to EAuthState.WaitCode,
        TdApi.AuthorizationStateWaitEncryptionKey.CONSTRUCTOR   to EAuthState.WaitEncryptionKey,
        TdApi.AuthorizationStateWaitPassword.CONSTRUCTOR        to EAuthState.WaitPassword,
        TdApi.AuthorizationStateWaitPhoneNumber.CONSTRUCTOR     to EAuthState.WaitPhoneNumber
)

val functionMap = mapOf(
        TdApi.AcceptCall.CONSTRUCTOR                             to  EFunction.AcceptCall,
        TdApi.AddChatMember.CONSTRUCTOR                          to  EFunction.AddChatMember,
        TdApi.AddChatMembers.CONSTRUCTOR                         to  EFunction.AddChatMembers,
        TdApi.AddFavoriteSticker.CONSTRUCTOR                     to  EFunction.AddFavoriteSticker,
        TdApi.AddNetworkStatistics.CONSTRUCTOR                   to  EFunction.AddNetworkStatistics,
        TdApi.AddRecentSticker.CONSTRUCTOR                       to  EFunction.AddRecentSticker,
        TdApi.AddRecentlyFoundChat.CONSTRUCTOR                   to  EFunction.AddRecentlyFoundChat,
        TdApi.AddSavedAnimation.CONSTRUCTOR                      to  EFunction.AddSavedAnimation,
        TdApi.AddStickerToSet.CONSTRUCTOR                        to  EFunction.AddStickerToSet,
        TdApi.AnswerCallbackQuery.CONSTRUCTOR                    to  EFunction.AnswerCallbackQuery,
        TdApi.AnswerCustomQuery.CONSTRUCTOR                      to  EFunction.AnswerCustomQuery,
        TdApi.AnswerInlineQuery.CONSTRUCTOR                      to  EFunction.AnswerInlineQuery,
        TdApi.AnswerPreCheckoutQuery.CONSTRUCTOR                 to  EFunction.AnswerPreCheckoutQuery,
        TdApi.AnswerShippingQuery.CONSTRUCTOR                    to  EFunction.AnswerShippingQuery,
        TdApi.BlockUser.CONSTRUCTOR                              to  EFunction.BlockUser,
        TdApi.CancelDownloadFile.CONSTRUCTOR                     to  EFunction.CancelDownloadFile,
        TdApi.CancelUploadFile.CONSTRUCTOR                       to  EFunction.CancelUploadFile,
        TdApi.ChangeChatReportSpamState.CONSTRUCTOR              to  EFunction.ChangeChatReportSpamState,
        TdApi.ChangeImportedContacts.CONSTRUCTOR                 to  EFunction.ChangeImportedContacts,
        TdApi.ChangePhoneNumber.CONSTRUCTOR                      to  EFunction.ChangePhoneNumber,
        TdApi.ChangeStickerSet.CONSTRUCTOR                       to  EFunction.ChangeStickerSet,
        TdApi.CheckAuthenticationBotToken.CONSTRUCTOR            to  EFunction.CheckAuthenticationBotToken,
        TdApi.CheckAuthenticationCode.CONSTRUCTOR                to  EFunction.CheckAuthenticationCode,
        TdApi.CheckAuthenticationPassword.CONSTRUCTOR            to  EFunction.CheckAuthenticationPassword,
        TdApi.CheckChangePhoneNumberCode.CONSTRUCTOR             to  EFunction.CheckChangePhoneNumberCode,
        TdApi.CheckChatInviteLink.CONSTRUCTOR                    to  EFunction.CheckChatInviteLink,
        TdApi.CheckChatUsername.CONSTRUCTOR                      to  EFunction.CheckChatUsername,
        TdApi.CheckDatabaseEncryptionKey.CONSTRUCTOR             to  EFunction.CheckDatabaseEncryptionKey,
        TdApi.ClearImportedContacts.CONSTRUCTOR                  to  EFunction.ClearImportedContacts,
        TdApi.ClearRecentStickers.CONSTRUCTOR                    to  EFunction.ClearRecentStickers,
        TdApi.ClearRecentlyFoundChats.CONSTRUCTOR                to  EFunction.ClearRecentlyFoundChats,
        TdApi.Close.CONSTRUCTOR                                  to  EFunction.Close,
        TdApi.CloseChat.CONSTRUCTOR                              to  EFunction.CloseChat,
        TdApi.CloseSecretChat.CONSTRUCTOR                        to  EFunction.CloseSecretChat,
        TdApi.CreateBasicGroupChat.CONSTRUCTOR                   to  EFunction.CreateBasicGroupChat,
        TdApi.CreateCall.CONSTRUCTOR                             to  EFunction.CreateCall,
        TdApi.CreateNewBasicGroupChat.CONSTRUCTOR                to  EFunction.CreateNewBasicGroupChat,
        TdApi.CreateNewSecretChat.CONSTRUCTOR                    to  EFunction.CreateNewSecretChat,
        TdApi.CreateNewStickerSet.CONSTRUCTOR                    to  EFunction.CreateNewStickerSet,
        TdApi.CreateNewSupergroupChat.CONSTRUCTOR                to  EFunction.CreateNewSupergroupChat,
        TdApi.CreatePrivateChat.CONSTRUCTOR                      to  EFunction.CreatePrivateChat,
        TdApi.CreateSecretChat.CONSTRUCTOR                       to  EFunction.CreateSecretChat,
        TdApi.CreateSupergroupChat.CONSTRUCTOR                   to  EFunction.CreateSupergroupChat,
        TdApi.CreateTemporaryPassword.CONSTRUCTOR                to  EFunction.CreateTemporaryPassword,
        TdApi.DeleteAccount.CONSTRUCTOR                          to  EFunction.DeleteAccount,
        TdApi.DeleteChatHistory.CONSTRUCTOR                      to  EFunction.DeleteChatHistory,
        TdApi.DeleteChatMessagesFromUser.CONSTRUCTOR             to  EFunction.DeleteChatMessagesFromUser,
        TdApi.DeleteChatReplyMarkup.CONSTRUCTOR                  to  EFunction.DeleteChatReplyMarkup,
        TdApi.DeleteFile.CONSTRUCTOR                             to  EFunction.DeleteFile,
        TdApi.DeleteMessages.CONSTRUCTOR                         to  EFunction.DeleteMessages,
        TdApi.DeleteProfilePhoto.CONSTRUCTOR                     to  EFunction.DeleteProfilePhoto,
        TdApi.DeleteSavedCredentials.CONSTRUCTOR                 to  EFunction.DeleteSavedCredentials,
        TdApi.DeleteSavedOrderInfo.CONSTRUCTOR                   to  EFunction.DeleteSavedOrderInfo,
        TdApi.DeleteSupergroup.CONSTRUCTOR                       to  EFunction.DeleteSupergroup,
        TdApi.Destroy.CONSTRUCTOR                                to  EFunction.Destroy,
        TdApi.DiscardCall.CONSTRUCTOR                            to  EFunction.DiscardCall,
        TdApi.DisconnectAllWebsites.CONSTRUCTOR                  to  EFunction.DisconnectAllWebsites,
        TdApi.DisconnectWebsite.CONSTRUCTOR                      to  EFunction.DisconnectWebsite,
        TdApi.DownloadFile.CONSTRUCTOR                           to  EFunction.DownloadFile,
        TdApi.EditInlineMessageCaption.CONSTRUCTOR               to  EFunction.EditInlineMessageCaption,
        TdApi.EditInlineMessageLiveLocation.CONSTRUCTOR          to  EFunction.EditInlineMessageLiveLocation,
        TdApi.EditInlineMessageReplyMarkup.CONSTRUCTOR           to  EFunction.EditInlineMessageReplyMarkup,
        TdApi.EditInlineMessageText.CONSTRUCTOR                  to  EFunction.EditInlineMessageText,
        TdApi.EditMessageCaption.CONSTRUCTOR                     to  EFunction.EditMessageCaption,
        TdApi.EditMessageLiveLocation.CONSTRUCTOR                to  EFunction.EditMessageLiveLocation,
        TdApi.EditMessageReplyMarkup.CONSTRUCTOR                 to  EFunction.EditMessageReplyMarkup,
        TdApi.EditMessageText.CONSTRUCTOR                        to  EFunction.EditMessageText,
        TdApi.FinishFileGeneration.CONSTRUCTOR                   to  EFunction.FinishFileGeneration,
        TdApi.ForwardMessages.CONSTRUCTOR                        to  EFunction.ForwardMessages,
        TdApi.GenerateChatInviteLink.CONSTRUCTOR                 to  EFunction.GenerateChatInviteLink,
        TdApi.GetAccountTtl.CONSTRUCTOR                          to  EFunction.GetAccountTtl,
        TdApi.GetActiveLiveLocationMessages.CONSTRUCTOR          to  EFunction.GetActiveLiveLocationMessages,
        TdApi.GetActiveSessions.CONSTRUCTOR                      to  EFunction.GetActiveSessions,
        TdApi.GetArchivedStickerSets.CONSTRUCTOR                 to  EFunction.GetArchivedStickerSets,
        TdApi.GetAttachedStickerSets.CONSTRUCTOR                 to  EFunction.GetAttachedStickerSets,
        TdApi.GetAuthorizationState.CONSTRUCTOR                  to  EFunction.GetAuthorizationState,
        TdApi.GetBasicGroup.CONSTRUCTOR                          to  EFunction.GetBasicGroup,
        TdApi.GetBasicGroupFullInfo.CONSTRUCTOR                  to  EFunction.GetBasicGroupFullInfo,
        TdApi.GetBlockedUsers.CONSTRUCTOR                        to  EFunction.GetBlockedUsers,
        TdApi.GetCallbackQueryAnswer.CONSTRUCTOR                 to  EFunction.GetCallbackQueryAnswer,
        TdApi.GetChat.CONSTRUCTOR                                to  EFunction.GetChat,
        TdApi.GetChatAdministrators.CONSTRUCTOR                  to  EFunction.GetChatAdministrators,
        TdApi.GetChatEventLog.CONSTRUCTOR                        to  EFunction.GetChatEventLog,
        TdApi.GetChatHistory.CONSTRUCTOR                         to  EFunction.GetChatHistory,
        TdApi.GetChatMember.CONSTRUCTOR                          to  EFunction.GetChatMember,
        TdApi.GetChatMessageByDate.CONSTRUCTOR                   to  EFunction.GetChatMessageByDate,
        TdApi.GetChatPinnedMessage.CONSTRUCTOR                   to  EFunction.GetChatPinnedMessage,
        TdApi.GetChatReportSpamState.CONSTRUCTOR                 to  EFunction.GetChatReportSpamState,
        TdApi.GetChats.CONSTRUCTOR                               to  EFunction.GetChats,
        TdApi.GetConnectedWebsites.CONSTRUCTOR                   to  EFunction.GetConnectedWebsites,
        TdApi.GetCountryCode.CONSTRUCTOR                         to  EFunction.GetCountryCode,
        TdApi.GetCreatedPublicChats.CONSTRUCTOR                  to  EFunction.GetCreatedPublicChats,
        TdApi.GetFavoriteStickers.CONSTRUCTOR                    to  EFunction.GetFavoriteStickers,
        TdApi.GetFile.CONSTRUCTOR                                to  EFunction.GetFile,
        TdApi.GetFileExtension.CONSTRUCTOR                       to  EFunction.GetFileExtension,
        TdApi.GetFileMimeType.CONSTRUCTOR                        to  EFunction.GetFileMimeType,
        TdApi.GetGameHighScores.CONSTRUCTOR                      to  EFunction.GetGameHighScores,
        TdApi.GetGroupsInCommon.CONSTRUCTOR                      to  EFunction.GetGroupsInCommon,
        TdApi.GetImportedContactCount.CONSTRUCTOR                to  EFunction.GetImportedContactCount,
        TdApi.GetInlineGameHighScores.CONSTRUCTOR                to  EFunction.GetInlineGameHighScores,
        TdApi.GetInlineQueryResults.CONSTRUCTOR                  to  EFunction.GetInlineQueryResults,
        TdApi.GetInstalledStickerSets.CONSTRUCTOR                to  EFunction.GetInstalledStickerSets,
        TdApi.GetInviteText.CONSTRUCTOR                          to  EFunction.GetInviteText,
        TdApi.GetMe.CONSTRUCTOR                                  to  EFunction.GetMe,
        TdApi.GetMessage.CONSTRUCTOR                             to  EFunction.GetMessage,
        TdApi.GetMessages.CONSTRUCTOR                            to  EFunction.GetMessages,
        TdApi.GetNetworkStatistics.CONSTRUCTOR                   to  EFunction.GetNetworkStatistics,
        TdApi.GetNotificationSettings.CONSTRUCTOR                to  EFunction.GetNotificationSettings,
        TdApi.GetOption.CONSTRUCTOR                              to  EFunction.GetOption,
        TdApi.GetPasswordState.CONSTRUCTOR                       to  EFunction.GetPasswordState,
        TdApi.GetPaymentForm.CONSTRUCTOR                         to  EFunction.GetPaymentForm,
        TdApi.GetPaymentReceipt.CONSTRUCTOR                      to  EFunction.GetPaymentReceipt,
        TdApi.GetProxy.CONSTRUCTOR                               to  EFunction.GetProxy,
        TdApi.GetPublicMessageLink.CONSTRUCTOR                   to  EFunction.GetPublicMessageLink,
        TdApi.GetRecentInlineBots.CONSTRUCTOR                    to  EFunction.GetRecentInlineBots,
        TdApi.GetRecentStickers.CONSTRUCTOR                      to  EFunction.GetRecentStickers,
        TdApi.GetRecentlyVisitedTMeUrls.CONSTRUCTOR              to  EFunction.GetRecentlyVisitedTMeUrls,
        TdApi.GetRecoveryEmailAddress.CONSTRUCTOR                to  EFunction.GetRecoveryEmailAddress,
        TdApi.GetRemoteFile.CONSTRUCTOR                          to  EFunction.GetRemoteFile,
        TdApi.GetRepliedMessage.CONSTRUCTOR                      to  EFunction.GetRepliedMessage,
        TdApi.GetSavedAnimations.CONSTRUCTOR                     to  EFunction.GetSavedAnimations,
        TdApi.GetSavedOrderInfo.CONSTRUCTOR                      to  EFunction.GetSavedOrderInfo,
        TdApi.GetSecretChat.CONSTRUCTOR                          to  EFunction.GetSecretChat,
        TdApi.GetStickerEmojis.CONSTRUCTOR                       to  EFunction.GetStickerEmojis,
        TdApi.GetStickerSet.CONSTRUCTOR                          to  EFunction.GetStickerSet,
        TdApi.GetStickers.CONSTRUCTOR                            to  EFunction.GetStickers,
        TdApi.GetStorageStatistics.CONSTRUCTOR                   to  EFunction.GetStorageStatistics,
        TdApi.GetStorageStatisticsFast.CONSTRUCTOR               to  EFunction.GetStorageStatisticsFast,
        TdApi.GetSupergroup.CONSTRUCTOR                          to  EFunction.GetSupergroup,
        TdApi.GetSupergroupFullInfo.CONSTRUCTOR                  to  EFunction.GetSupergroupFullInfo,
        TdApi.GetSupergroupMembers.CONSTRUCTOR                   to  EFunction.GetSupergroupMembers,
        TdApi.GetSupportUser.CONSTRUCTOR                         to  EFunction.GetSupportUser,
        TdApi.GetTemporaryPasswordState.CONSTRUCTOR              to  EFunction.GetTemporaryPasswordState,
        TdApi.GetTermsOfService.CONSTRUCTOR                      to  EFunction.GetTermsOfService,
        TdApi.GetTextEntities.CONSTRUCTOR                        to  EFunction.GetTextEntities,
        TdApi.GetTopChats.CONSTRUCTOR                            to  EFunction.GetTopChats,
        TdApi.GetTrendingStickerSets.CONSTRUCTOR                 to  EFunction.GetTrendingStickerSets,
        TdApi.GetUser.CONSTRUCTOR                                to  EFunction.GetUser,
        TdApi.GetUserFullInfo.CONSTRUCTOR                        to  EFunction.GetUserFullInfo,
        TdApi.GetUserPrivacySettingRules.CONSTRUCTOR             to  EFunction.GetUserPrivacySettingRules,
        TdApi.GetUserProfilePhotos.CONSTRUCTOR                   to  EFunction.GetUserProfilePhotos,
        TdApi.GetWallpapers.CONSTRUCTOR                          to  EFunction.GetWallpapers,
        TdApi.GetWebPageInstantView.CONSTRUCTOR                  to  EFunction.GetWebPageInstantView,
        TdApi.GetWebPagePreview.CONSTRUCTOR                      to  EFunction.GetWebPagePreview,
        TdApi.ImportContacts.CONSTRUCTOR                         to  EFunction.ImportContacts,
        TdApi.JoinChatByInviteLink.CONSTRUCTOR                   to  EFunction.JoinChatByInviteLink,
        TdApi.LogOut.CONSTRUCTOR                                 to  EFunction.LogOut,
        TdApi.OpenChat.CONSTRUCTOR                               to  EFunction.OpenChat,
        TdApi.OpenMessageContent.CONSTRUCTOR                     to  EFunction.OpenMessageContent,
        TdApi.OptimizeStorage.CONSTRUCTOR                        to  EFunction.OptimizeStorage,
        TdApi.ParseTextEntities.CONSTRUCTOR                      to  EFunction.ParseTextEntities,
        TdApi.PinSupergroupMessage.CONSTRUCTOR                   to  EFunction.PinSupergroupMessage,
        TdApi.ProcessDcUpdate.CONSTRUCTOR                        to  EFunction.ProcessDcUpdate,
        TdApi.ReadAllChatMentions.CONSTRUCTOR                    to  EFunction.ReadAllChatMentions,
        TdApi.RecoverAuthenticationPassword.CONSTRUCTOR          to  EFunction.RecoverAuthenticationPassword,
        TdApi.RecoverPassword.CONSTRUCTOR                        to  EFunction.RecoverPassword,
        TdApi.RegisterDevice.CONSTRUCTOR                         to  EFunction.RegisterDevice,
        TdApi.RemoveContacts.CONSTRUCTOR                         to  EFunction.RemoveContacts,
        TdApi.RemoveFavoriteSticker.CONSTRUCTOR                  to  EFunction.RemoveFavoriteSticker,
        TdApi.RemoveRecentHashtag.CONSTRUCTOR                    to  EFunction.RemoveRecentHashtag,
        TdApi.RemoveRecentSticker.CONSTRUCTOR                    to  EFunction.RemoveRecentSticker,
        TdApi.RemoveRecentlyFoundChat.CONSTRUCTOR                to  EFunction.RemoveRecentlyFoundChat,
        TdApi.RemoveSavedAnimation.CONSTRUCTOR                   to  EFunction.RemoveSavedAnimation,
        TdApi.RemoveStickerFromSet.CONSTRUCTOR                   to  EFunction.RemoveStickerFromSet,
        TdApi.RemoveTopChat.CONSTRUCTOR                          to  EFunction.RemoveTopChat,
        TdApi.ReorderInstalledStickerSets.CONSTRUCTOR            to  EFunction.ReorderInstalledStickerSets,
        TdApi.ReportChat.CONSTRUCTOR                             to  EFunction.ReportChat,
        TdApi.ReportSupergroupSpam.CONSTRUCTOR                   to  EFunction.ReportSupergroupSpam,
        TdApi.RequestAuthenticationPasswordRecovery.CONSTRUCTOR  to  EFunction.RequestAuthenticationPasswordRecovery,
        TdApi.RequestPasswordRecovery.CONSTRUCTOR                to  EFunction.RequestPasswordRecovery,
        TdApi.ResendAuthenticationCode.CONSTRUCTOR               to  EFunction.ResendAuthenticationCode,
        TdApi.ResendChangePhoneNumberCode.CONSTRUCTOR            to  EFunction.ResendChangePhoneNumberCode,
        TdApi.ResetAllNotificationSettings.CONSTRUCTOR           to  EFunction.ResetAllNotificationSettings,
        TdApi.ResetNetworkStatistics.CONSTRUCTOR                 to  EFunction.ResetNetworkStatistics,
        TdApi.SearchCallMessages.CONSTRUCTOR                     to  EFunction.SearchCallMessages,
        TdApi.SearchChatMembers.CONSTRUCTOR                      to  EFunction.SearchChatMembers,
        TdApi.SearchChatMessages.CONSTRUCTOR                     to  EFunction.SearchChatMessages,
        TdApi.SearchChatRecentLocationMessages.CONSTRUCTOR       to  EFunction.SearchChatRecentLocationMessages,
        TdApi.SearchChats.CONSTRUCTOR                            to  EFunction.SearchChats,
        TdApi.SearchChatsOnServer.CONSTRUCTOR                    to  EFunction.SearchChatsOnServer,
        TdApi.SearchContacts.CONSTRUCTOR                         to  EFunction.SearchContacts,
        TdApi.SearchHashtags.CONSTRUCTOR                         to  EFunction.SearchHashtags,
        TdApi.SearchInstalledStickerSets.CONSTRUCTOR             to  EFunction.SearchInstalledStickerSets,
        TdApi.SearchMessages.CONSTRUCTOR                         to  EFunction.SearchMessages,
        TdApi.SearchPublicChat.CONSTRUCTOR                       to  EFunction.SearchPublicChat,
        TdApi.SearchPublicChats.CONSTRUCTOR                      to  EFunction.SearchPublicChats,
        TdApi.SearchSecretMessages.CONSTRUCTOR                   to  EFunction.SearchSecretMessages,
        TdApi.SearchStickerSet.CONSTRUCTOR                       to  EFunction.SearchStickerSet,
        TdApi.SearchStickerSets.CONSTRUCTOR                      to  EFunction.SearchStickerSets,
        TdApi.SearchStickers.CONSTRUCTOR                         to  EFunction.SearchStickers,
        TdApi.SendBotStartMessage.CONSTRUCTOR                    to  EFunction.SendBotStartMessage,
        TdApi.SendCallDebugInformation.CONSTRUCTOR               to  EFunction.SendCallDebugInformation,
        TdApi.SendCallRating.CONSTRUCTOR                         to  EFunction.SendCallRating,
        TdApi.SendChatAction.CONSTRUCTOR                         to  EFunction.SendChatAction,
        TdApi.SendChatScreenshotTakenNotification.CONSTRUCTOR    to  EFunction.SendChatScreenshotTakenNotification,
        TdApi.SendChatSetTtlMessage.CONSTRUCTOR                  to  EFunction.SendChatSetTtlMessage,
        TdApi.SendCustomRequest.CONSTRUCTOR                      to  EFunction.SendCustomRequest,
        TdApi.SendInlineQueryResultMessage.CONSTRUCTOR           to  EFunction.SendInlineQueryResultMessage,
        TdApi.SendMessage.CONSTRUCTOR                            to  EFunction.SendMessage,
        TdApi.SendMessageAlbum.CONSTRUCTOR                       to  EFunction.SendMessageAlbum,
        TdApi.SendPaymentForm.CONSTRUCTOR                        to  EFunction.SendPaymentForm,
        TdApi.SetAccountTtl.CONSTRUCTOR                          to  EFunction.SetAccountTtl,
        TdApi.SetAlarm.CONSTRUCTOR                               to  EFunction.SetAlarm,
        TdApi.SetAuthenticationPhoneNumber.CONSTRUCTOR           to  EFunction.SetAuthenticationPhoneNumber,
        TdApi.SetBio.CONSTRUCTOR                                 to  EFunction.SetBio,
        TdApi.SetBotUpdatesStatus.CONSTRUCTOR                    to  EFunction.SetBotUpdatesStatus,
        TdApi.SetChatClientData.CONSTRUCTOR                      to  EFunction.SetChatClientData,
        TdApi.SetChatDraftMessage.CONSTRUCTOR                    to  EFunction.SetChatDraftMessage,
        TdApi.SetChatMemberStatus.CONSTRUCTOR                    to  EFunction.SetChatMemberStatus,
        TdApi.SetChatPhoto.CONSTRUCTOR                           to  EFunction.SetChatPhoto,
        TdApi.SetChatTitle.CONSTRUCTOR                           to  EFunction.SetChatTitle,
        TdApi.SetDatabaseEncryptionKey.CONSTRUCTOR               to  EFunction.SetDatabaseEncryptionKey,
        TdApi.SetFileGenerationProgress.CONSTRUCTOR              to  EFunction.SetFileGenerationProgress,
        TdApi.SetGameScore.CONSTRUCTOR                           to  EFunction.SetGameScore,
        TdApi.SetInlineGameScore.CONSTRUCTOR                     to  EFunction.SetInlineGameScore,
        TdApi.SetName.CONSTRUCTOR                                to  EFunction.SetName,
        TdApi.SetNetworkType.CONSTRUCTOR                         to  EFunction.SetNetworkType,
        TdApi.SetNotificationSettings.CONSTRUCTOR                to  EFunction.SetNotificationSettings,
        TdApi.SetOption.CONSTRUCTOR                              to  EFunction.SetOption,
        TdApi.SetPassword.CONSTRUCTOR                            to  EFunction.SetPassword,
        TdApi.SetPinnedChats.CONSTRUCTOR                         to  EFunction.SetPinnedChats,
        TdApi.SetProfilePhoto.CONSTRUCTOR                        to  EFunction.SetProfilePhoto,
        TdApi.SetProxy.CONSTRUCTOR                               to  EFunction.SetProxy,
        TdApi.SetRecoveryEmailAddress.CONSTRUCTOR                to  EFunction.SetRecoveryEmailAddress,
        TdApi.SetStickerPositionInSet.CONSTRUCTOR                to  EFunction.SetStickerPositionInSet,
        TdApi.SetSupergroupDescription.CONSTRUCTOR               to  EFunction.SetSupergroupDescription,
        TdApi.SetSupergroupStickerSet.CONSTRUCTOR                to  EFunction.SetSupergroupStickerSet,
        TdApi.SetSupergroupUsername.CONSTRUCTOR                  to  EFunction.SetSupergroupUsername,
        TdApi.SetTdlibParameters.CONSTRUCTOR                     to  EFunction.SetTdlibParameters,
        TdApi.SetUserPrivacySettingRules.CONSTRUCTOR             to  EFunction.SetUserPrivacySettingRules,
        TdApi.SetUsername.CONSTRUCTOR                            to  EFunction.SetUsername,
        TdApi.TerminateAllOtherSessions.CONSTRUCTOR              to  EFunction.TerminateAllOtherSessions,
        TdApi.TerminateSession.CONSTRUCTOR                       to  EFunction.TerminateSession,
        TdApi.TestCallBytes.CONSTRUCTOR                          to  EFunction.TestCallBytes,
        TdApi.TestCallEmpty.CONSTRUCTOR                          to  EFunction.TestCallEmpty,
        TdApi.TestCallString.CONSTRUCTOR                         to  EFunction.TestCallString,
        TdApi.TestCallVectorInt.CONSTRUCTOR                      to  EFunction.TestCallVectorInt,
        TdApi.TestCallVectorIntObject.CONSTRUCTOR                to  EFunction.TestCallVectorIntObject,
        TdApi.TestCallVectorString.CONSTRUCTOR                   to  EFunction.TestCallVectorString,
        TdApi.TestCallVectorStringObject.CONSTRUCTOR             to  EFunction.TestCallVectorStringObject,
        TdApi.TestGetDifference.CONSTRUCTOR                      to  EFunction.TestGetDifference,
        TdApi.TestNetwork.CONSTRUCTOR                            to  EFunction.TestNetwork,
        TdApi.TestSquareInt.CONSTRUCTOR                          to  EFunction.TestSquareInt,
        TdApi.TestUseError.CONSTRUCTOR                           to  EFunction.TestUseError,
        TdApi.TestUseUpdate.CONSTRUCTOR                          to  EFunction.TestUseUpdate,
        TdApi.ToggleBasicGroupAdministrators.CONSTRUCTOR         to  EFunction.ToggleBasicGroupAdministrators,
        TdApi.ToggleChatIsPinned.CONSTRUCTOR                     to  EFunction.ToggleChatIsPinned,
        TdApi.ToggleSupergroupInvites.CONSTRUCTOR                to  EFunction.ToggleSupergroupInvites,
        TdApi.ToggleSupergroupIsAllHistoryAvailable.CONSTRUCTOR  to  EFunction.ToggleSupergroupIsAllHistoryAvailable,
        TdApi.ToggleSupergroupSignMessages.CONSTRUCTOR           to  EFunction.ToggleSupergroupSignMessages,
        TdApi.UnblockUser.CONSTRUCTOR                            to  EFunction.UnblockUser,
        TdApi.UnpinSupergroupMessage.CONSTRUCTOR                 to  EFunction.UnpinSupergroupMessage,
        TdApi.UpgradeBasicGroupChatToSupergroupChat.CONSTRUCTOR  to  EFunction.UpgradeBasicGroupChatToSupergroupChat,
        TdApi.UploadFile.CONSTRUCTOR                             to  EFunction.UploadFile,
        TdApi.UploadStickerFile.CONSTRUCTOR                      to  EFunction.UploadStickerFile,
        TdApi.ValidateOrderInfo.CONSTRUCTOR                      to  EFunction.ValidateOrderInfo,
        TdApi.ViewMessages.CONSTRUCTOR                           to  EFunction.ViewMessages,
        TdApi.ViewTrendingStickerSets.CONSTRUCTOR                to  EFunction.ViewTrendingStickerSets
)

val updateMap = mapOf(
        TdApi.UpdateAuthorizationState.CONSTRUCTOR       to  EUpdate.UpdateAuthorizationState,
        TdApi.UpdateNewMessage.CONSTRUCTOR               to  EUpdate.UpdateNewMessage,
        TdApi.UpdateMessageSendAcknowledged.CONSTRUCTOR  to  EUpdate.UpdateMessageSendAcknowledged,
        TdApi.UpdateMessageSendSucceeded.CONSTRUCTOR     to  EUpdate.UpdateMessageSendSucceeded,
        TdApi.UpdateMessageSendFailed.CONSTRUCTOR        to  EUpdate.UpdateMessageSendFailed,
        TdApi.UpdateMessageContent.CONSTRUCTOR           to  EUpdate.UpdateMessageContent,
        TdApi.UpdateMessageEdited.CONSTRUCTOR            to  EUpdate.UpdateMessageEdited,
        TdApi.UpdateMessageViews.CONSTRUCTOR             to  EUpdate.UpdateMessageViews,
        TdApi.UpdateMessageContentOpened.CONSTRUCTOR     to  EUpdate.UpdateMessageContentOpened,
        TdApi.UpdateMessageMentionRead.CONSTRUCTOR       to  EUpdate.UpdateMessageMentionRead,
        TdApi.UpdateNewChat.CONSTRUCTOR                  to  EUpdate.UpdateNewChat,
        TdApi.UpdateChatTitle.CONSTRUCTOR                to  EUpdate.UpdateChatTitle,
        TdApi.UpdateChatPhoto.CONSTRUCTOR                to  EUpdate.UpdateChatPhoto,
        TdApi.UpdateChatLastMessage.CONSTRUCTOR          to  EUpdate.UpdateChatLastMessage,
        TdApi.UpdateChatOrder.CONSTRUCTOR                to  EUpdate.UpdateChatOrder,
        TdApi.UpdateChatIsPinned.CONSTRUCTOR             to  EUpdate.UpdateChatIsPinned,
        TdApi.UpdateChatReadInbox.CONSTRUCTOR            to  EUpdate.UpdateChatReadInbox,
        TdApi.UpdateChatReadOutbox.CONSTRUCTOR           to  EUpdate.UpdateChatReadOutbox,
        TdApi.UpdateChatUnreadMentionCount.CONSTRUCTOR   to  EUpdate.UpdateChatUnreadMentionCount,
        TdApi.UpdateNotificationSettings.CONSTRUCTOR     to  EUpdate.UpdateNotificationSettings,
        TdApi.UpdateChatReplyMarkup.CONSTRUCTOR          to  EUpdate.UpdateChatReplyMarkup,
        TdApi.UpdateChatDraftMessage.CONSTRUCTOR         to  EUpdate.UpdateChatDraftMessage,
        TdApi.UpdateDeleteMessages.CONSTRUCTOR           to  EUpdate.UpdateDeleteMessages,
        TdApi.UpdateUserChatAction.CONSTRUCTOR           to  EUpdate.UpdateUserChatAction,
        TdApi.UpdateUserStatus.CONSTRUCTOR               to  EUpdate.UpdateUserStatus,
        TdApi.UpdateUser.CONSTRUCTOR                     to  EUpdate.UpdateUser,
        TdApi.UpdateBasicGroup.CONSTRUCTOR               to  EUpdate.UpdateBasicGroup,
        TdApi.UpdateSupergroup.CONSTRUCTOR               to  EUpdate.UpdateSupergroup,
        TdApi.UpdateSecretChat.CONSTRUCTOR               to  EUpdate.UpdateSecretChat,
        TdApi.UpdateUserFullInfo.CONSTRUCTOR             to  EUpdate.UpdateUserFullInfo,
        TdApi.UpdateBasicGroupFullInfo.CONSTRUCTOR       to  EUpdate.UpdateBasicGroupFullInfo,
        TdApi.UpdateSupergroupFullInfo.CONSTRUCTOR       to  EUpdate.UpdateSupergroupFullInfo,
        TdApi.UpdateServiceNotification.CONSTRUCTOR      to  EUpdate.UpdateServiceNotification,
        TdApi.UpdateFile.CONSTRUCTOR                     to  EUpdate.UpdateFile,
        TdApi.UpdateFileGenerationStart.CONSTRUCTOR      to  EUpdate.UpdateFileGenerationStart,
        TdApi.UpdateFileGenerationStop.CONSTRUCTOR       to  EUpdate.UpdateFileGenerationStop,
        TdApi.UpdateCall.CONSTRUCTOR                     to  EUpdate.UpdateCall,
        TdApi.UpdateUserPrivacySettingRules.CONSTRUCTOR  to  EUpdate.UpdateUserPrivacySettingRules,
        TdApi.UpdateUnreadMessageCount.CONSTRUCTOR       to  EUpdate.UpdateUnreadMessageCount,
        TdApi.UpdateOption.CONSTRUCTOR                   to  EUpdate.UpdateOption,
        TdApi.UpdateInstalledStickerSets.CONSTRUCTOR     to  EUpdate.UpdateInstalledStickerSets,
        TdApi.UpdateTrendingStickerSets.CONSTRUCTOR      to  EUpdate.UpdateTrendingStickerSets,
        TdApi.UpdateRecentStickers.CONSTRUCTOR           to  EUpdate.UpdateRecentStickers,
        TdApi.UpdateFavoriteStickers.CONSTRUCTOR         to  EUpdate.UpdateFavoriteStickers,
        TdApi.UpdateSavedAnimations.CONSTRUCTOR          to  EUpdate.UpdateSavedAnimations,
        TdApi.UpdateConnectionState.CONSTRUCTOR          to  EUpdate.UpdateConnectionState,
        TdApi.UpdateNewInlineQuery.CONSTRUCTOR           to  EUpdate.UpdateNewInlineQuery,
        TdApi.UpdateNewChosenInlineResult.CONSTRUCTOR    to  EUpdate.UpdateNewChosenInlineResult,
        TdApi.UpdateNewCallbackQuery.CONSTRUCTOR         to  EUpdate.UpdateNewCallbackQuery,
        TdApi.UpdateNewInlineCallbackQuery.CONSTRUCTOR   to  EUpdate.UpdateNewInlineCallbackQuery,
        TdApi.UpdateNewShippingQuery.CONSTRUCTOR         to  EUpdate.UpdateNewShippingQuery,
        TdApi.UpdateNewPreCheckoutQuery.CONSTRUCTOR      to  EUpdate.UpdateNewPreCheckoutQuery,
        TdApi.UpdateNewCustomEvent.CONSTRUCTOR           to  EUpdate.UpdateNewCustomEvent,
        TdApi.UpdateNewCustomQuery.CONSTRUCTOR           to  EUpdate.UpdateNewCustomQuery
)

val notifSettingScopeMap = mapOf(
        TdApi.NotificationSettingsScopeChat.CONSTRUCTOR             to  ENotificationSettingScope.NotificationSettingsScopeChat,
        TdApi.NotificationSettingsScopePrivateChats.CONSTRUCTOR     to  ENotificationSettingScope.NotificationSettingsScopePrivateChats,
        TdApi.NotificationSettingsScopeBasicGroupChats.CONSTRUCTOR  to  ENotificationSettingScope.NotificationSettingsScopeBasicGroupChats,
        TdApi.NotificationSettingsScopeAllChats.CONSTRUCTOR         to  ENotificationSettingScope.NotificationSettingsScopeAllChats
)